service: webftp

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'demo'}
  region: ${env:region, 'eu-west-1'}
  memorySize: 128
  stackTags:
    ci: ${file(env/${self:service}.${self:provider.stage}.json):ci}
    UOCEnv: ${file(env/${self:service}.${self:provider.stage}.json):UOCEnv}
    Departament: ${file(env/${self:service}.${self:provider.stage}.json):Departament}
    Programa: ${file(env/${self:service}.${self:provider.stage}.json):Programa}
    name: ${self:service}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource: "*"
    #- Effect: 'Allow'
    #  Action:
    #    - sts:AssumeRole
    #  Resource: "*"
  apiGateway:
    shouldStartNameWithService: true

  environment:
    #ROLE: { "Fn::GetAtt" : [ "IamRoleLambdaExecution", "Arn" ] }
    #ORIGIN: https://${self:custom.frontBucket}.s3-${self:provider.region}.amazonaws.com
    ORIGIN: "*"

resources:
  Resources:
    S3FrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: Origin Access Identity to Access Website Bucket
    S3PublicDataOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: Origin Access Identity to Access Public Data Bucket
    S3ProtectedDataOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: Origin Access Identity to Access Protected Data Bucket
    ApiGatewayAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: Origin Access Identity to Access API Gateway

    S3FrontCloudFront:
      Type: AWS::CloudFront::Distribution
      DependsOn:
        - S3Front
        - ApiGatewayRestApi
        - S3ProtectedData
      Properties:
        DistributionConfig:
          Origins:
            - Id: S3Origin
              DomainName:
                Fn::Join:
                  - ''
                  - - ${self:custom.frontBucket}
                    - '.s3-${self:provider.region}.amazonaws.com'
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - /
                    - - origin-access-identity
                      - cloudfront
                      - Ref: "S3FrontOriginAccessIdentity"
            - Id: ApiGatewayOrigin
              DomainName:
                Fn::Join:
                  - ''
                  - - Ref: "ApiGatewayRestApi"
                    - '.execute-api.'
                    - ${self:provider.region}
                    - '.amazonaws.com'
              OriginPath: /${self:provider.stage}
              CustomOriginConfig:
                OriginProtocolPolicy: 'https-only'
            - Id: S3ProtectedOrigin
              DomainName:
                Fn::Join:
                  - ''
                  - - ${self:custom.protectedDataBucket}
                    - '.s3-${self:provider.region}.amazonaws.com'
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - /
                    - - origin-access-identity
                      - cloudfront
                      - Ref: "S3ProtectedDataOriginAccessIdentity"
          CustomErrorResponses:
            - ErrorCachingMinTTL: 0
              ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html

          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0

          CacheBehaviors:
            - TargetOriginId: ApiGatewayOrigin
              ViewerProtocolPolicy: 'https-only'
              DefaultTTL: 0
              MaxTTL: 0
              MinTTL: 0
              ForwardedValues:
                QueryString: true
                Cookies:
                  Forward: all
                Headers:
                  - Referer
                  - Authorization
              AllowedMethods:
                - GET
                - HEAD
                - OPTIONS
                - PUT
                - POST
                - PATCH
                - DELETE
              PathPattern: ${self:custom.apiPath}/*
          DefaultRootObject: index.html
          Enabled: true
          ViewerCertificate:
            AcmCertificateArn: ${self:custom.domainCertArn}
            MinimumProtocolVersion: TLSv1.1_2016
            SslSupportMethod: sni-only
          Aliases:
            - ${self:custom.domain}

#    S3DNSName:
#      Type: AWS::Route53::RecordSetGroup
#      Properties:
#        HostedZoneId: Z000460910O4UQFOKDCIH
#        RecordSets:
#          - Name: ${self:custom.delegatedDomain}
#            Type: A
#            AliasTarget:
#                HostedZoneId: Z2FDTNDATAQYW2
#                DNSName:
#                  Fn::GetAtt: [ "S3FrontCloudFront", "DomainName" ]
#                EvaluateTargetHealth: false

    S3PublicCdnCloudFront:
      Type: AWS::CloudFront::Distribution
      DependsOn:
        - S3PublicData
      Properties:
        DistributionConfig:
          Origins:
            - Id: S3PublicDataOrigin
              DomainName:
                Fn::Join:
                  - ''
                  - - ${self:custom.publicDataBucket}
                    - '.s3-${self:provider.region}.amazonaws.com'
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - /
                    - - origin-access-identity
                      - cloudfront
                      - Ref: "S3PublicDataOriginAccessIdentity"
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
            TargetOriginId: S3PublicDataOrigin
            ViewerProtocolPolicy: redirect-to-https
#            DefaultTTL: 3600
#            MaxTTL: 86400
#            MinTTL: 0
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
          DefaultRootObject: index.html
          Enabled: true
          ViewerCertificate:
            AcmCertificateArn: ${self:custom.publicCdnDomainCertArn}
            MinimumProtocolVersion: TLSv1.1_2016
            SslSupportMethod: sni-only
          Aliases:
            - ${self:custom.publicCdnDomain}

    # S3PublicCdnDNSName:
    #   Type: AWS::Route53::RecordSetGroup
    #   Properties:
    #     HostedZoneId: Z000460910O4UQFOKDCIH
    #     RecordSets:
    #       - Name: ${self:custom.publicCdnDomain}
    #         Type: A
    #         AliasTarget:
    #             HostedZoneId: Z2FDTNDATAQYW2
    #             DNSName:
    #               Fn::GetAtt: [ "S3PublicCdnCloudFront", "DomainName" ]
    #             EvaluateTargetHealth: false

    S3ProtectedCdnCloudFront:
      Type: AWS::CloudFront::Distribution
      DependsOn:
        - S3ProtectedData
      Properties:
        DistributionConfig:
          Origins:
            - Id: S3ProtectedDataOrigin
              DomainName:
                Fn::Join:
                  - ''
                  - - ${self:custom.protectedDataBucket}
                    - '.s3-${self:provider.region}.amazonaws.com'
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - /
                    - - origin-access-identity
                      - cloudfront
                      - Ref: "S3ProtectedDataOriginAccessIdentity"
          CustomErrorResponses:
            - ErrorCachingMinTTL: 0
              ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /error/index.html

          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
            TargetOriginId: S3ProtectedDataOrigin
            ViewerProtocolPolicy: redirect-to-https
#            DefaultTTL: 3600
#            MaxTTL: 86400
#            MinTTL: 0
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            TrustedSigners:
              - 755686861862
          DefaultRootObject: index.html
          Enabled: true
          ViewerCertificate:
            AcmCertificateArn: ${self:custom.protectedCdnDomainCertArn}
            MinimumProtocolVersion: TLSv1.1_2016
            SslSupportMethod: sni-only
          Aliases:
            - ${self:custom.protectedCdnDomain}

#    S3ProtectedCdnDNSName:
#      Type: AWS::Route53::RecordSetGroup
#      Properties:
#        HostedZoneId: Z000460910O4UQFOKDCIH
#        RecordSets:
#          - Name: ${self:custom.protectedCdnDomain}
#            Type: A
#            AliasTarget:
#                HostedZoneId: Z2FDTNDATAQYW2
#                DNSName:
#                  Fn::GetAtt: [ "S3ProtectedCdnCloudFront", "DomainName" ]
#                EvaluateTargetHealth: false

    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

    S3PublicData:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.publicDataBucket}
        VersioningConfiguration:
          Status: Enabled
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - POST
                - HEAD
              AllowedOrigins:
                #- https://${self:custom.frontBucket}.s3-website-${self:provider.region}.amazonaws.com
                - "*"
    S3PublicDataBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: S3PublicData
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                CanonicalUser:
                  Fn::GetAtt: [ S3PublicDataOriginAccessIdentity , S3CanonicalUserId ]
              Action: "s3:GetObject"
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "S3PublicData"
                    },
                    "/*"
                  ]
                ]               
                # !Join
                #   - ""
                #   - - Fn::GetAtt: [S3PublicData, Arn]
                #     - "/*"            

    S3ProtectedData:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.protectedDataBucket}
        VersioningConfiguration:
          Status: Enabled
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - POST
                - HEAD
              AllowedOrigins:
                #- https://${self:custom.frontBucket}.s3-website-${self:provider.region}.amazonaws.com
                - "*"
    S3ProtectedDataBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: S3ProtectedData
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                CanonicalUser:
                  Fn::GetAtt: [ S3ProtectedDataOriginAccessIdentity , S3CanonicalUserId ]
              Action: "s3:GetObject"
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "S3ProtectedData"
                    },
                    "/*"
                  ]
                ]               
                # !Join
                #   - ""
                #   - - Fn::GetAtt: [S3ProtectedData, Arn]
                #     - "/*"

    S3Front:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.frontBucket}
        VersioningConfiguration:
          Status: Enabled

    FrontEndBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: S3Front
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                CanonicalUser:
                  Fn::GetAtt: [ S3FrontOriginAccessIdentity , S3CanonicalUserId ]
              Action: "s3:GetObject"
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "S3Front"
                    },
                    "/*"
                  ]
                ]               
                # !Join
                #   - ""
                #   - - Fn::GetAtt: [S3Front, Arn]
                #     - "/*"
    
    S3Authz:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.authzBucket}
        VersioningConfiguration:
          Status: Enabled
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - POST
                - HEAD
              AllowedOrigins:
                - "*"   

functions:
  browse:
    handler: browsing/index.handler
    events:
      - http:
          path: ${self:custom.apiPath}/getfiles
          method: get
          cors: true
          authorizer:
            name: custom-auth
            resultTtlInSeconds: 1

  delete:
    handler: delete-keys/index.handler
    events:
      - http:
          path: ${self:custom.apiPath}/deletekeys
          method: post
          cors: true
          authorizer:
            name: custom-auth
            resultTtlInSeconds: 1
    timeout: 30

  upload:
    handler: form-signing-sdk/index.handler
    events:
      - http:
          path: ${self:custom.apiPath}/getuploadform
          method: get
          cors: true
          authorizer:
            name: custom-auth
            resultTtlInSeconds: 1

  download:
    handler: get-presigned-urls/index.handler
    events:
      - http:
          path: ${self:custom.apiPath}/getpresignedurls
          method: post
          cors: true
          authorizer:
            name: custom-auth
            resultTtlInSeconds: 1

  login:
    handler: login/app.handler
    events:
      - http:
          path: ${self:custom.apiPath}/{proxy+}
          method: any
          cors: true

    environment:
      ALLOWED_DOMAINS: ${self:custom.domain},${self:custom.frontBucket}-${self:provider.stage}.s3-${self:provider.region}.amazonaws.com,localhost:8080
      IDP_HOST: ${self:custom.idpHost, "samltest.id"}
      JWT_SAML_PROFILE:  urn:oid:2.5.4.42, urn:oid:0.9.2342.19200300.100.1.3, urn:oid:2.16.840.1.113730.3.1.241
      JWT_SECRET: ${self:custom.jwtSecret, "12345678"}
      SAML_CERT: ${self:custom.samlCert, "MIIDEjCCAfqgAwIBAgIVAMECQ1tjghafm5OxWDh9hwZfxthWMA0GCSqGSIb3DQEB CwUAMBYxFDASBgNVBAMMC3NhbWx0ZXN0LmlkMB4XDTE4MDgyNDIxMTQwOVoXDTM4 MDgyNDIxMTQwOVowFjEUMBIGA1UEAwwLc2FtbHRlc3QuaWQwggEiMA0GCSqGSIb3 DQEBAQUAA4IBDwAwggEKAoIBAQC0Z4QX1NFKs71ufbQwoQoW7qkNAJRIANGA4iM0 ThYghul3pC+FwrGv37aTxWXfA1UG9njKbbDreiDAZKngCgyjxj0uJ4lArgkr4AOE jj5zXA81uGHARfUBctvQcsZpBIxDOvUUImAl+3NqLgMGF2fktxMG7kX3GEVNc1kl bN3dfYsaw5dUrw25DheL9np7G/+28GwHPvLb4aptOiONbCaVvh9UMHEA9F7c0zfF /cL5fOpdVa54wTI0u12CsFKt78h6lEGG5jUs/qX9clZncJM7EFkN3imPPy+0HC8n spXiH/MZW8o2cqWRkrw3MzBZW3Ojk5nQj40V6NUbjb7kfejzAgMBAAGjVzBVMB0G A1UdDgQWBBQT6Y9J3Tw/hOGc8PNV7JEE4k2ZNTA0BgNVHREELTArggtzYW1sdGVz dC5pZIYcaHR0cHM6Ly9zYW1sdGVzdC5pZC9zYW1sL2lkcDANBgkqhkiG9w0BAQsF AAOCAQEASk3guKfTkVhEaIVvxEPNR2w3vWt3fwmwJCccW98XXLWgNbu3YaMb2RSn 7Th4p3h+mfyk2don6au7Uyzc1Jd39RNv80TG5iQoxfCgphy1FYmmdaSfO8wvDtHT TNiLArAxOYtzfYbzb5QrNNH/gQEN8RJaEf/g/1GTw9x/103dSMK0RXtl+fRs2nbl D1JJKSQ3AdhxK/weP3aUPtLxVVJ9wMOQOfcy02l+hHMb6uAjsPOpOVKqi3M8XmcU ZOpx4swtgGdeoSpeRyrtMvRwdcciNBp9UZome44qZAYH1iqrpmmjsfI9pJItsgWu 3kXPjhSfj1AJGR1l9JGvJrHki1iHTA=="}
      SAML_DOMAIN: ${self:custom.domain}
#      SAML_DOMAIN:
#        Fn::Join
#          - ''
#          - - !Ref ApiGatewayRestApi
#            - '.execute-api.'
#            - ${self:provider.region}
#            - '.amazonaws.com'
      SAML_ISSUER: saml-jwt-${self:service}-${self:provider.stage}
      API_PATH: ${self:custom.apiPath}
      STAGE: ${self:provider.stage}

  custom-auth:
    handler: custom-auth/index.handler
    environment:
      JWT_SECRET: ${self:custom.jwtSecret, "12345678"}
      BUCKET: ${self:custom.authzBucket}
      FILE: permissions.csv

  getConfig:
    handler: get-config/index.handler
    events:
      - http:
          path: ${self:custom.apiPath}/getconfig
          method: get
          cors: true
    environment:
      PUBLIC_DATA_BUCKET: ${self:custom.publicDataBucket}
      PROTECTED_DATA_BUCKET: ${self:custom.protectedDataBucket}
      PUBLIC_CDN_DOMAIN: ${self:custom.publicCdnDomain}
      PROTECTED_CDN_DOMAIN: ${self:custom.protectedCdnDomain}

custom:
  frontBucket: ${self:service}-web-${self:provider.stage}
  authzBucket: ${self:service}-authz-${self:provider.stage}
  publicDataBucket: ${self:service}-files-${self:provider.stage}
  protectedDataBucket: ${self:service}-protected-files-${self:provider.stage}
  jwtSecret: ${ssm:/${self:provider.stage}/${self:service}/JWT_SECRET}
  samlCert: ${ssm:/${self:provider.stage}/${self:service}/SAML_CERT}
  idpHost: ${file(env/${self:service}.${self:provider.stage}.json):IDP_HOST}
  apiPath: ${file(env/${self:service}.${self:provider.stage}.json):API_PATH, '/api'}
  domain: ${file(env/${self:service}.${self:provider.stage}.json):DOMAIN}
  domainCertArn: ${file(env/${self:service}.${self:provider.stage}.json):DOMAIN_CERT_ARN}
  publicCdnDomain: ${file(env/${self:service}.${self:provider.stage}.json):PUBLIC_CDN_DOMAIN}
  publicCdnDomainCertArn: ${file(env/${self:service}.${self:provider.stage}.json):PUBLIC_CDN_DOMAIN_CERT_ARN}
  protectedCdnDomain: ${file(env/${self:service}.${self:provider.stage}.json):PROTECTED_CDN_DOMAIN}
  protectedCdnDomainCertArn: ${file(env/${self:service}.${self:provider.stage}.json):PROTECTED_CDN_DOMAIN_CERT_ARN}

package:
  exclude:
    - node_modules/**
    - frontend/**
    - data/**
