on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  #   paths: [ 'backend/**' ]
  # pull_request:
  #   branches: [main]
  #   paths: [ 'backend/**' ]

jobs:
  cicd-application:
    name: Execute AWS CodePipeline
    runs-on: ubuntu-latest
    environment: Demo
    defaults:
      run:
        working-directory: ./petclinic
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0

      #- name: Fix detected dubious ownership in repository at '/github/workspace' error
      #  run: git config --global --add safe.directory /github/workspace

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Sync up to CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@v1.0.6
        with:
          repository_name: petclinic
          aws_region: eu-west-1

      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        if: github.ref == 'refs/heads/master'
        with:
          aws-region: "eu-west-1"
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          pipeline-name: "petclinic-master-Pipeline"