on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [ 'frontend/**', 'admin/**' ]
  pull_request:
    branches: [main]
    paths: [ 'frontend/**', 'admin/**' ]

jobs:
  cicd-application:
    name: Sync S3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    environment: Demo
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd ./frontend && npm ci && npm run build

      - name: Deploy static site to S3 bucket
        env:
          STAGE: ${{ vars.STAGE }}
        run: aws s3 sync ./frontend/dist/ s3://webftp-web-$STAGE --delete && aws s3 cp ./admin/error/index.html s3://webftp-protected-files-$STAGE/error/index.html
